# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    env_file: 
      - ./env/mongodb.env
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes: 
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./env/backend_nodejs.env
    depends_on:
      - mongodb
volumes: 
  data:
